import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Gallery, Hero } from '@/components'

const galleryItems = [
  { id: 1, imageUrl: "https://fakeimg.pl/600x400", isDouble: false },
  { id: 2, imageUrl: "https://fakeimg.pl/600x400", isDouble: false },
  { id: 3, imageUrl: "https://fakeimg.pl/800x400", isDouble: true },
  { id: 4, imageUrl: "https://fakeimg.pl/600x400", isDouble: false },
  { id: 5, imageUrl: "https://fakeimg.pl/800x400", isDouble: true },
  { id: 6, imageUrl: "https://fakeimg.pl/600x400", isDouble: false },
  { id: 7, imageUrl: "https://fakeimg.pl/600x400", isDouble: false },
  // ... other gallery items
];


export default function Home() {
  return (
    <>
      <Head>
        <title>SK Studios</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/sk-logo-bg.png" />
      </Head>
      <Hero />
      <main className={`${styles.container}`}>
        <Gallery pictures={galleryItems} />
      </main>
    </>
  )
}
