import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { Footer, Gallery, Hero, Services } from '@/components'

const galleryItems = [
  { id: 1, imageUrl: "https://fakeimg.pl/600x400", isDouble: false },
  { id: 2, imageUrl: "https://fakeimg.pl/600x400", isDouble: false },
  { id: 3, imageUrl: "https://fakeimg.pl/800x400", isDouble: true },
  { id: 4, imageUrl: "https://fakeimg.pl/600x400", isDouble: false },
  { id: 5, imageUrl: "https://fakeimg.pl/800x400", isDouble: true },
  { id: 6, imageUrl: "https://fakeimg.pl/600x400", isDouble: false }
];

const services = [
  {
    title: 'test',
    description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Velit vitae modi laborum esse excepturi repudiandae consequatur sint sunt quis ut rerum asperiores cupiditate, debitis nemo officiis ea officia eveniet maxime!'
  },
  {
    title: 'test',
    description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Velit vitae modi laborum esse excepturi repudiandae consequatur sint sunt quis ut rerum asperiores cupiditate, debitis nemo officiis ea officia eveniet maxime!'
  },
  {
    title: 'test',
    description: 'Lorem, ipsum dolor sit amet consectetur adipisicing elit. Velit vitae modi laborum esse excepturi repudiandae consequatur sint sunt quis ut rerum asperiores cupiditate, debitis nemo officiis ea officia eveniet maxime!'
  }
]


export default function Home() {
  return (
    <>
      <Head>
        <title>SK Studios</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/sk-logo-bg.png" />
      </Head>
      <Hero />
      <main className={`${styles.container}`}>

        <div>
          <Services {...{ data: services }} />
        </div>
        <Gallery pictures={galleryItems} />
      </main>

      <Footer />
    </>
  )
}
