import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { BookingSelect, Navbar } from '@/components'

const options = [
    { option_name: 'option1', price: '20' },
    { option_name: 'option2', price: '40' },
    { option_name: 'option3', price: '60' }
]

export default function BookingPreview() {
    return (
        <>
            <Head>
                <title>SK Studios - Booking a session</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/sk-logo-bg.png" />
            </Head>

            <Navbar />
            <main className={styles.container}>
                <BookingSelect {...{ options }} />
            </main>
        </>
    )
}
